const properties = [
  { id: '1', name: '3 Bedroom Bungalow', city: 'Asaba', price: 'N45,00000', image: '/assets/featured-img.jpg' },
  { id: '2', name: '3 Bedroom Bungalow', city: 'Asaba', price: 'N45,00000', image: '/assets/featured-img.jpg' },
  { id: '3', name: '3 Bedroom Bungalow', city: 'Asaba', price: 'N45,00000', image: '/assets/featured-img.jpg' },
  { id: '4', name: '3 Bedroom Bungalow', city: 'Asaba', price: 'N45,00000', image: '/assets/featured-img.jpg' },
  { id: '5', name: '3 Bedroom Bungalow', city: 'Asaba', price: 'N45,00000', image: '/assets/featured-img.jpg' },
  { id: '6', name: '3 Bedroom Bungalow', city: 'Asaba', price: 'N45,00000', image: '/assets/featured-img.jpg' },
  { id: '7', name: '3 Bedroom Bungalow', city: 'Asaba', price: 'N45,00000', image: '/assets/featured-img.jpg' },
  { id: '8', name: '3 Bedroom Bungalow', city: 'Asaba', price: 'N45,00000', image: '/assets/featured-img.jpg' },
  { id: '9', name: '3 Bedroom Bungalow', city: 'Asaba', price: 'N45,00000', image: '/assets/featured-img.jpg' },
  { id: '10', name: '3 Bedroom Bungalow', city: 'Asaba', price: 'N45,00000', image: '/assets/featured-img.jpg' },
  { id: '11', name: '3 Bedroom Bungalow', city: 'Asaba', price: 'N45,00000', image: '/assets/featured-img.jpg' },
  { id: '12', name: '3 Bedroom Bungalow', city: 'Asaba', price: 'N45,00000', image: '/assets/featured-img.jpg' },
  { id: '13', name: '3 Bedroom Bungalow', city: 'Asaba', price: 'N45,00000', image: '/assets/featured-img.jpg' },
  { id: '14', name: '3 Bedroom Bungalow', city: 'Asaba', price: 'N45,00000', image: '/assets/featured-img.jpg' },
  { id: '15', name: '3 Bedroom Bungalow', city: 'Asaba', price: 'N45,00000', image: '/assets/featured-img.jpg' },
  { id: '16', name: '3 Bedroom Bungalow', city: 'Asaba', price: 'N45,00000', image: '/assets/featured-img.jpg' },
  { id: '17', name: '3 Bedroom Bungalow', city: 'Asaba', price: 'N45,00000', image: '/assets/featured-img.jpg' },
  { id: '18', name: '3 Bedroom Bungalow', city: 'Asaba', price: 'N45,00000', image: '/assets/featured-img.jpg' },
  { id: '19', name: '3 Bedroom Bungalow', city: 'Asaba', price: 'N45,00000', image: '/assets/featured-img.jpg' },
  { id: '20', name: '3 Bedroom Bungalow', city: 'Asaba', price: 'N45,00000', image: '/assets/featured-img.jpg' },
  { id: '21', name: '3 Bedroom Bungalow', city: 'Asaba', price: 'N45,00000', image: '/assets/featured-img.jpg' },
  { id: '22', name: '3 Bedroom Bungalow', city: 'Asaba', price: 'N45,00000', image: '/assets/featured-img.jpg' },
   { id: '17', name: '3 Bedroom Bungalow', city: 'Asaba', price: 'N45,00000', image: '/assets/featured-img.jpg' },
  { id: '18', name: '3 Bedroom Bungalow', city: 'Asaba', price: 'N45,00000', image: '/assets/featured-img.jpg' },
  { id: '19', name: '3 Bedroom Bungalow', city: 'Asaba', price: 'N45,00000', image: '/assets/featured-img.jpg' },
  { id: '20', name: '3 Bedroom Bungalow', city: 'Asaba', price: 'N45,00000', image: '/assets/featured-img.jpg' },
  { id: '21', name: '3 Bedroom Bungalow', city: 'Asaba', price: 'N45,00000', image: '/assets/featured-img.jpg' },
  { id: '22', name: '3 Bedroom Bungalow', city: 'Asaba', price: 'N45,00000', image: '/assets/featured-img.jpg' },
  { id: '21', name: '3 Bedroom Bungalow', city: 'Asaba', price: 'N45,00000', image: '/assets/featured-img.jpg' },
  { id: '22', name: '3 Bedroom Bungalow', city: 'Asaba', price: 'N45,00000', image: '/assets/featured-img.jpg' },
   { id: '17', name: '3 Bedroom Bungalow', city: 'Asaba', price: 'N45,00000', image: '/assets/featured-img.jpg' },
  { id: '18', name: '3 Bedroom Bungalow', city: 'Asaba', price: 'N45,00000', image: '/assets/featured-img.jpg' },
  { id: '19', name: '3 Bedroom Bungalow', city: 'Asaba', price: 'N45,00000', image: '/assets/featured-img.jpg' },
  { id: '20', name: '3 Bedroom Bungalow', city: 'Asaba', price: 'N45,00000', image: '/assets/featured-img.jpg' },
  { id: '21', name: '3 Bedroom Bungalow', city: 'Asaba', price: 'N45,00000', image: '/assets/featured-img.jpg' },
  { id: '22', name: '3 Bedroom Bungalow', city: 'Asaba', price: 'N45,00000', image: '/assets/featured-img.jpg' },
  
]
module.exports = properties;